### ISSUE TITLE
Ballot unlock: Copy missing

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf4-voting-ui#109]
On the ballot unlock page the copy of "Your voting category is [CATEGORY] ([Number of projects])." is missing as well as the Pairwise reference. See implementation and designs below

<img width="1316" alt="Screenshot 2024-09-18 at 12 38 30" src="https://github.com/user-attachments/assets/42bacaef-28bf-4cac-b736-32c8fe012b7e">

Designs
<img width="356" alt="Screenshot 2024-09-18 at 12 38 46" src="https://github.com/user-attachments/assets/6ea24045-3a4f-4e21-8345-6e3966a551c9">

**Comment by shaunop** [comment]
For the Pairwise reference, we've [updated the designs ](https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU?node-id=8207-117442#954159395)to...

1. Include logo as requested 
2. Remove the upload button
3. The whole tile can be clickable and open in a new tab, since there's only one path. Link to https://www.pairwise.vote/retrofunding5

<img width="756" alt="Screenshot 2024-09-18 at 9 14 00 AM" src="https://github.com/user-attachments/assets/9087f473-ae47-4bd8-89a0-0eb8e30cc298">

Pairwise logo asset:
![pairwise-logo 1](https://github.com/user-attachments/assets/281da7a8-ecf3-4b8a-a7c3-d2eaf7d018ac)
