### ISSUE TITLE
Ballot should reflect budget amount in subtext

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf4-voting-ui#180]
Ballot should reflect correct budget amount in subtext. Note the third line ... "OP calculations in this ballot are based on your budget of {number} OP". It's currently inaccurate.

<img width="1085" alt="Screenshot 2024-09-23 at 11 25 11 AM" src="https://github.com/user-attachments/assets/5063d599-060b-4711-bb57-f5c5b7fccdf2">

**Comment by vidvidvid** [comment]
@shaunop can you please check if this is still an issue?
this might be the case if the person doesn't allocate their budget beforehand, could you confirm?

**Comment by shaunop** [comment]
Looks good now!

**Comment by vidvidvid** [comment]
> The text, "OP calculations in this ballot are based on [your category budget of 0 OP" is not accurate. This seems to be an issue when you first unlock your ballot. After I refreshed the page it displayed the correct value

**Comment by JSeiferth** [comment]
Could we fix this in a way that the number is updated without requiring a refresh of the page? 

Also highlighted here https://github.com/grants-stack-frontier/op-rf4-voting-ui/issues/235

**Comment by vidvidvid** [comment]
@JSeiferth i'm positive this has finally been fixed with the PR i just merged. i checked it multiple times and it works - please let me know if you're still encountering this issue. the fix will be live in about 10 minutes: https://develop-op-voting.up.railway.app/ballot

**Comment by JSeiferth** [comment]
@vidvidvid just had another user report this. 
This happens when you leave the category allocations unchanged (e.g. leave them in the default of 33.33% each)


<img width="1264" alt="Screenshot 2024-09-27 at 16 09 56" src="https://github.com/user-attachments/assets/886ab33a-da45-4c4a-9e05-7a8f0a0ba3bb">

![telegram-cloud-photo-size-4-6032890585460885015-y](https://github.com/user-attachments/assets/cbf91c2a-fe02-43e9-8167-61785ee7cfd3)

**Comment by vidvidvid** [comment]
@JSeiferth gotcha, i suspected that might be the case. will push a fix tomorrow.
it's a related issue, so i'll open a new issue for it.
